source 'https://rubygems.org'

# Standard gems
gem 'rails', '4.2.1'
gem 'mysql2'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'therubyracer', platforms: :ruby
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'spring',        group: :development
gem 'rake', '< 11.0'

# UI
gem 'bootstrap3-rails'
gem 'font-awesome-rails'
gem 'jquery-turbolinks'
gem 'jquery-tokeninput-rails'

# User modeling
gem 'devise'

# User Stamp
gem 'clerk'

# Deal with files
gem 'rubyzip'
gem 'ruby-filemagic'
gem 'dimensions'

# Context Menus
gem 'jquery_context_menu-rails'

# Search
gem 'ransack'

group :development do
  gem 'capistrano', '~> 3.6.1'
  gem 'capistrano-rbenv'
  gem 'capistrano-rbenv-install'
  gem 'capistrano-rails'
  gem 'capistrano-bundler'
  gem 'capistrano-passenger'
  gem 'capistrano-secrets-yml'
  gem 'capistrano-scm-jenkins'
end

group :production do
  gem 'passenger'
end

group :test do
  gem 'minitest'
  gem 'rspec-rails'
  gem 'capybara'
  gem 'cucumber-rails', require: false
  gem 'database_cleaner'
  gem 'factory_girl_rails'
  gem 'ci_reporter_minitest'
  gem 'ci_reporter_cucumber'
  gem 'launchy'
  gem 'simplecov', :require => false
  gem 'simplecov-rcov', :require => false
  gem 'poltergeist'
  gem 'selenium-webdriver'
  gem 'pry'
  gem 'rspec-expectations'
  gem 'show_me_the_cookies'
  gem 'metric_fu'
end
