source 'https://rubygems.org'


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.1'
# Use mysql as the database for Active Record
gem 'mysql2'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.1.0'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0', group: :doc

# Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
gem 'spring',        group: :development

# Bootstrap UI
gem 'bootstrap3-rails'
gem 'font-awesome-rails'

# User modeling
gem 'devise'

# User Stamp
gem 'clerk'

# Zipfile
gem 'rubyzip'

# Context Menu
gem 'jquery_context_menu-rails'

# Deployment
group :development do
  gem 'capistrano', '~> 3.2.1'
  gem 'capistrano-rbenv', '~> 2.0'
  gem 'capistrano-rbenv-install', '~> 1.2.0'
  gem 'capistrano-rails', '~> 1.1'
  gem 'capistrano-passenger'
  gem 'capistrano-secrets-yml'
  gem 'capistrano-scm-jenkins', '~> 0.5.0'
end

# Production
group :production do
  gem 'passenger'
end

# Test
group :test do
  gem 'minitest'
  gem 'rspec-rails'
  gem 'capybara'
  gem 'cucumber-rails', require: false
  gem 'database_cleaner'
  gem 'ci_reporter_minitest'
  gem 'ci_reporter_cucumber'
  gem 'factory_girl_rails'
  gem 'poltergeist'
  gem 'selenium-webdriver'
  gem 'pry'
  gem 'rspec-expectations'
  gem 'launchy'
  gem "show_me_the_cookies"
  gem 'simplecov', :require => false
  gem 'simplecov-rcov', :require => false
  gem 'metric_fu'
end
